### ISSUE TITLE
How to combine multiple mods?

### ISSUE THREAD

**Issue by aminought** [luetage/vivaldi_modding#1]
I don't understand, how to combine multiple mods? Create mentioned user.css and user.js and copy-paste fragments of files or somehow include them via code?

**Comment by luetage** [comment]
Hey, you make one user.css file and just paste all css code into it. – That's all there is to it in case of css. For javascript you could do pretty much the same – paste everything into one js file and be done with it. But since there is some kind of loop needed to initialise the functions, you would paste multiple loops that do all the same thing. Therefore it's enough to paste all the functions and below one single loop and in this loop you call all functions. For example if you're using tabScroll.js you would call tabScroll() there etc. Just separate the calls by line and semicolon.

**Comment by luetage** [comment]
I'm gonna close this issue.
