### ISSUE TITLE
Extensions in statusbar not working for snapshot 3.5.2115.81 (Stable channel) (64-bit)

### ISSUE THREAD

**Issue by whereistejas** [luetage/vivaldi_modding#5]
Hi,

I'm getting the following error:
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at extStatus (ext-in-statusbar.js:52)
    at wait (ext-in-statusbar.js:60)
```

Is it possible that the css classname has changed? I tried using `statusbar-toolbar` instead of `footer` in the method extStatus, but even that failed.

**Comment by whereistejas** [comment]
On further analysis, I notice that the following const variable `wrapper` is blank if we hide the address bar field from the settings.

https://github.com/luetage/vivaldi_modding/blob/9019d7c7cb5ad1807bc6c0ebae4c064fc4b99fe1/move_extensions_to_status-bar.js#L56

**Comment by luetage** [comment]
Hey there.
Please look at the readme for a list of actively maintained mods. As for the mod in question… The main problem is the statusbar is being removed from the HTML entirely whenever it is being toggled, which makes the mod crash the entire UI. Nowadays instead of running the mod once at window creation, it would have to be loaded whenever the statusbar is being added and there would have to be additional triggers whenever the statusbar is being removed. That’s possible, I already do this in several other mods, which you can find in this repository. What makes everything worse is that the addressbar is likewise being removed, even when simply opening a mail tab, which breaks all of this too. In my opinion it’s not worth looking into, but if you really really want your extensions in the status bar I’m sure it’s possible to make it work somehow. Please ask for help on the forum, the link to the forum thread is at the top of the modification code. Feel free to reply to it, even if Vivaldi Forum should warn you the topic is old—it’s perfectly fine to bump it, that’s what it’s there for.

**Comment by whereistejas** [comment]
@luetage thanks :)
